### PR TITLE
Fix a11y of command results

### LINKED ISSUE #6: A11y: on:mouseover must be accompanied by on:focus
https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/master/docs/rules/mouse-events-have-key-events.md

https://github.com/oskarhane/actus/blob/cb8f2135b04380613afe734e0b26a65f17cadcbc/packages/svelte/src/Component.svelte#L211

### PR DESCRIPTION
**Pull request by ceifa**
I just repeated the code, but I think it's okay since it's a very small snippet

Fixes #6

### CODE REVIEW

**Comment by ceifa** [comment]
If accepted, can you release a new version of the packages?

**Comment by oskarhane** [comment]
🙇

**Comment by ceifa** [comment]
I just wanted to say, thanks a lot for creating this package, I will be looking forward to help improving it when possible! :)

**Comment by oskarhane** [comment]
@ceifa v2.3.0 is out now, thanks for contributing to it!

**Pull request merged**
